### ISSUE TITLE
(*Hint*) \hyperref not working

### ISSUE THREAD

**Issue by jthomasbarry** [jthomasbarry/aafmt#18]
(_Hint_) not linking to hints sections in some chapters. I noticed it in modular and equivalence relations chapters, in specific.

**Comment by davidfarmer** [comment]
Con you give sample URLs or environment numbers?
(Both here and in general when reporting an issue.)

**Comment by jthomasbarry** [comment]
Exercise 4.2.10 is an example of the issue

**Comment by davidfarmer** [comment]
Fixed.
The problem was section labels that contained underscores, such as modular_arithmetic.
I fixed the code: it is okay to use such labels.

The code now assumes that section labels contain only lower case letters and underscores.
Let me know if anything else occurs, and I'll take care of those cases, too.

**Comment by christhron** [comment]
Looks fine
